# docker-compose up --build --force-recreate

version: '3'
services:

  # CentOS [Workerman + Slim]
  cent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cent
    ports:
      - "888:888"
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 888
      DB_TYPE: pgsql
      DB_HOST: host.docker.internal
    env_file:
      - .env
    networks:
      - internal

  # Ubu [Workerman + Slim]
  ubu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubu
    ports:
      - "999:999"
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 999
      DB_TYPE: pgsql      
      DB_HOST: host.docker.internal
    env_file:
      - .env
    networks:
      - internal


  # wrk
  wrk:
    build:
      context: .
      dockerfile: Dockerfile.wrk
    container_name: wrk
    networks:
      - internal

  # MySQL
  # Will be started on host.docker.internal

  #db:
    #image: mysql:5.7.22
    #container_name: db
    #restart: unless-stopped
    #tty: true
    #ports:
    #  - "3306:3306"
    #environment:
    #  MYSQL_DATABASE: laravel
    #  MYSQL_ROOT_PASSWORD: your_mysql_root_password
    #  SERVICE_TAGS: dev
    #  SERVICE_NAME: mysql
    #networks:
    #  - app-network

#volumes:
 # www:
#    driver: host
#    driver_opts:
#      source: ./

networks:
  internal:
    driver: bridge
