# docker-compose up --build --force-recreate

version: '3'
services:

  sberprime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sberprime
    ports:
      - 80:80
    volumes:
      - ./log:/var/www/log
    environment:
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    driver: bridge
