# docker-compose up --build --force-recreate

version: '3'
services:

  # CentOS
  cent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cent
    ports:
      - "888:888"
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 888
      DB_TYPE: pgsql
      DB_HOST: 192.168.99.1
    env_file:
      - .env
    networks:
      - internal

  # Ubuntu
  ubu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubu
    ports:
      - "999:999"
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 999
      DB_TYPE: pgsql
      DB_HOST: 192.168.99.1
    env_file:
      - .env
    networks:
      - internal

  # wrk
  wrk:
    build:
      context: .
      dockerfile: Dockerfile.wrk
    container_name: wrk
    networks:
      - internal

networks:
  internal:
    driver: bridge
